using System;
using System.IO;
using System.Text;

namespace NiteCompiler.SourceGenerators;

internal sealed class SourceWriter
{
    private static readonly string[] Indentations = [string.Empty, "\t", "\t\t", "\t\t\t", "\t\t\t\t", "\t\t\t\t\t"]; 
    
    private readonly StringBuilder _writer = new();
    
    private int _indent = 0;
    private string _indentString = "";
    
    public void EnterScope()
    {
        _indent++;

        _indentString = Indentations.Length > _indent ? Indentations[_indent] : new string('\t', _indent);
    }

    public void EnterScope(string text)
    {
        WriteLine(text);
        EnterScope();
    }

    public void ExitScope()
    {
        _indent--;
        if (_indent < 0)
            throw new InvalidOperationException();
        
        _indentString = Indentations.Length > _indent ? Indentations[_indent] : new string('\t', _indent);
    }
    
    public void ExitScope(string text)
    {
        ExitScope();
        WriteLine(text);
    }

    public void WriteLine(string text)
    {
        _writer.AppendLine(_indentString + text);
    }

    public void WriteLine()
    {
        _writer.AppendLine();
    }

    public void WriteDisclaimer()
    {
        WriteLine("""
                  /// <auto-generated>
                  /// This code was generated by a tool.
                  /// NiteCompiler.SourceGenerators
                  /// </auto-generated>
                  """);
    }

    public override string ToString()
    {
        return _writer.ToString();
    }
}